"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK
from .httpclient import AsyncHttpClient, ClientOwner, HttpClient, close_clients
from .sdkconfiguration import SDKConfiguration
from .utils.logger import Logger, get_default_logger
from .utils.retries import RetryConfig
import httpx
from mollie_api_python_beta import models, utils
from mollie_api_python_beta._hooks import SDKHooks
from mollie_api_python_beta.balances import Balances
from mollie_api_python_beta.capabilities import Capabilities
from mollie_api_python_beta.captures import Captures
from mollie_api_python_beta.chargebacks import Chargebacks
from mollie_api_python_beta.client_links import ClientLinks
from mollie_api_python_beta.clients import Clients
from mollie_api_python_beta.customers import Customers
from mollie_api_python_beta.invoices import Invoices
from mollie_api_python_beta.mandates import Mandates
from mollie_api_python_beta.methods import Methods
from mollie_api_python_beta.onboarding import Onboarding
from mollie_api_python_beta.orders import Orders
from mollie_api_python_beta.organizations import Organizations
from mollie_api_python_beta.payment_links import PaymentLinks
from mollie_api_python_beta.payments import Payments
from mollie_api_python_beta.permissions import Permissions
from mollie_api_python_beta.profiles import Profiles
from mollie_api_python_beta.refunds import Refunds
from mollie_api_python_beta.settlements import Settlements
from mollie_api_python_beta.shipments import Shipments
from mollie_api_python_beta.subscriptions import Subscriptions
from mollie_api_python_beta.terminals import Terminals
from mollie_api_python_beta.types import OptionalNullable, UNSET
from mollie_api_python_beta.wallets import Wallets
from typing import Callable, Dict, Optional, Union, cast
import weakref


class Mollie(BaseSDK):
    balances: Balances
    settlements: Settlements
    invoices: Invoices
    permissions: Permissions
    organizations: Organizations
    profiles: Profiles
    onboarding: Onboarding
    capabilities: Capabilities
    clients: Clients
    client_links: ClientLinks
    orders: Orders
    shipments: Shipments
    payments: Payments
    methods: Methods
    refunds: Refunds
    chargebacks: Chargebacks
    captures: Captures
    wallets: Wallets
    payment_links: PaymentLinks
    terminals: Terminals
    customers: Customers
    mandates: Mandates
    subscriptions: Subscriptions

    def __init__(
        self,
        security: Optional[
            Union[models.Security, Callable[[], models.Security]]
        ] = None,
        server_idx: Optional[int] = None,
        server_url: Optional[str] = None,
        url_params: Optional[Dict[str, str]] = None,
        client: Optional[HttpClient] = None,
        async_client: Optional[AsyncHttpClient] = None,
        retry_config: OptionalNullable[RetryConfig] = UNSET,
        timeout_ms: Optional[int] = None,
        debug_logger: Optional[Logger] = None,
    ) -> None:
        r"""Instantiates the SDK configuring it with the provided parameters.

        :param security: The security details required for authentication
        :param server_idx: The index of the server to use for all methods
        :param server_url: The server URL to use for all methods
        :param url_params: Parameters to optionally template the server URL with
        :param client: The HTTP client to use for all synchronous methods
        :param async_client: The Async HTTP client to use for all asynchronous methods
        :param retry_config: The retry configuration to use for all supported methods
        :param timeout_ms: Optional request timeout applied to each operation in milliseconds
        """
        if client is None:
            client = httpx.Client()

        assert issubclass(
            type(client), HttpClient
        ), "The provided client must implement the HttpClient protocol."

        if async_client is None:
            async_client = httpx.AsyncClient()

        if debug_logger is None:
            debug_logger = get_default_logger()

        assert issubclass(
            type(async_client), AsyncHttpClient
        ), "The provided async_client must implement the AsyncHttpClient protocol."

        if server_url is not None:
            if url_params is not None:
                server_url = utils.template_url(server_url, url_params)

        BaseSDK.__init__(
            self,
            SDKConfiguration(
                client=client,
                async_client=async_client,
                security=security,
                server_url=server_url,
                server_idx=server_idx,
                retry_config=retry_config,
                timeout_ms=timeout_ms,
                debug_logger=debug_logger,
            ),
        )

        hooks = SDKHooks()

        current_server_url, *_ = self.sdk_configuration.get_server_details()
        server_url, self.sdk_configuration.client = hooks.sdk_init(
            current_server_url, self.sdk_configuration.client
        )
        if current_server_url != server_url:
            self.sdk_configuration.server_url = server_url

        # pylint: disable=protected-access
        self.sdk_configuration.__dict__["_hooks"] = hooks

        weakref.finalize(
            self,
            close_clients,
            cast(ClientOwner, self.sdk_configuration),
            self.sdk_configuration.client,
            self.sdk_configuration.async_client,
        )

        self._init_sdks()

    def _init_sdks(self):
        self.balances = Balances(self.sdk_configuration)
        self.settlements = Settlements(self.sdk_configuration)
        self.invoices = Invoices(self.sdk_configuration)
        self.permissions = Permissions(self.sdk_configuration)
        self.organizations = Organizations(self.sdk_configuration)
        self.profiles = Profiles(self.sdk_configuration)
        self.onboarding = Onboarding(self.sdk_configuration)
        self.capabilities = Capabilities(self.sdk_configuration)
        self.clients = Clients(self.sdk_configuration)
        self.client_links = ClientLinks(self.sdk_configuration)
        self.orders = Orders(self.sdk_configuration)
        self.shipments = Shipments(self.sdk_configuration)
        self.payments = Payments(self.sdk_configuration)
        self.methods = Methods(self.sdk_configuration)
        self.refunds = Refunds(self.sdk_configuration)
        self.chargebacks = Chargebacks(self.sdk_configuration)
        self.captures = Captures(self.sdk_configuration)
        self.wallets = Wallets(self.sdk_configuration)
        self.payment_links = PaymentLinks(self.sdk_configuration)
        self.terminals = Terminals(self.sdk_configuration)
        self.customers = Customers(self.sdk_configuration)
        self.mandates = Mandates(self.sdk_configuration)
        self.subscriptions = Subscriptions(self.sdk_configuration)

    def __enter__(self):
        return self

    async def __aenter__(self):
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        if self.sdk_configuration.client is not None:
            self.sdk_configuration.client.close()

    async def __aexit__(self, exc_type, exc_val, exc_tb):
        if self.sdk_configuration.async_client is not None:
            await self.sdk_configuration.async_client.aclose()
