workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Mollie API:
        inputs:
            - location: https://raw.githubusercontent.com/mollie/openapi-specs/main/specs.yaml
              authHeader: Authorization
              authSecret: $openapi_doc_auth_token
        registry:
            location: registry.speakeasyapi.dev/mollie-oom/mollie/mollie-api
targets:
    client:
        target: python
        source: Mollie API
        publish:
            pypi:
                token: $pypi_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/mollie-oom/mollie/mollie-api-python-code-samples
            labelOverride:
                fixedValue: Python (SDK)
            blocking: false
