workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Mollie API:
        inputs:
            - location: ../../openapi-specs/mol-public-api/v2/specs.yaml
        registry:
            location: registry.speakeasyapi.dev/mollie-oom/mollie/mollie-api
targets:
    client:
        target: python
        source: Mollie API
        publish:
            pypi:
                token: $pypi_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/mollie-oom/mollie/mollie-api-python-code-samples
            labelOverride:
                fixedValue: Python (SDK)
            blocking: false
